paths:
  traffic_data: "data/raw/traffic/"
  transport_data: "data/raw/transport/"
  output_dir: "data/output/"
  logs_dir: "data/logs/"
  processed_dir: "data/processed/"
logging:
  level: "INFO"
  file: "data/logs/transport_analysis.log"
